import React from 'react'
import Button from '../Button'
import ListItem from '../ListItem'
import img from '@/public/assets/5.png'
import SpotlightCard from '../SpotlightCard'
import img1 from '@/public/assets/11.webp'
import img2 from '@/public/assets/12.webp'


const FeaturesSpotlights = (props) => {
    return (
        <section className=" bg-[#eff4fe] pt-32">
            <div className="container max-w-xl p-6 py-0 mx-auto space-y-16 text-gray-400 lg:px-8 lg:max-w-7xl">
                <div data-aos="fade-down">
                    <h1 className="text-3xl font-bold tracking-tight text-center sm:text-5xl text-[#323232]">Features spotlights</h1>
                </div>
                <div className=' flex flex-col gap-16 justify-center items-center p-20'>
                    <SpotlightCard title ={props.lang ? "Find Your Perfect Match with Ease." : "Encuentra el fabricante perfecto con facilidad."} subtitle = {props.lang ? "Our Platform Offers Advanced Search and Filtering Capabilities to Help Find Manufacturers That Meet Your Specific Needs." : "Nuestra plataforma ofrece capacidades avanzadas de búsqueda y filtrado pa' que encuentres fabricantes que cumplan con tus necesidades específicas."} overview = {props.lang ? "Puente offers a powerful platform that allows US buyers to easily find suppliers that perfectly match their specific requirements. Our platform comes equipped with advanced search and filtering capabilities that allow users to browse suppliers based on a variety of criteria, including location, industry, certifications, and more. With our streamlined platform, discovering quality manufacturers in Mexico has never been easier!" : "Puente ofrece una plataforma poderosa que permite a los compradores de EE. UU. encontrar fácilmente proveedores que se ajusten perfectamente a sus requisitos específicos. Nuestra plataforma cuenta con capacidades avanzadas de búsqueda y filtrado que permiten a los usuarios navegar entre proveedores según diversos criterios, como ubicación, industria, certificaciones y más. ¡Descubrir fábricas chidas en México nunca ha sido tan fácil!"} image = {img1}/>
                    <SpotlightCard title ={props.lang ? "Get the Information You Need to Make Informed Decisions." : "Toda la info para tomar decisiones informadas."} subtitle = {props.lang ? "Our Comprehensive Supplier Profiles Include All the Information You Need to Evaluate Each Manufacturer and Make an Informed Decision." : "Nuestros perfiles de proveedores incluyen toda la info que necesitas pa' evaluar a cada fabricante y tomar una decisión informada."} overview = {props.lang ? "When it comes to finding a manufacturer, it's important to have all the information you need to make informed decisions. With Puente, you can take the guesswork out of supplier selection with accurate information and complete reviews and ratings of each partner in our network. Our comprehensive supplier profiles offer insights into manufacturers' experience, capacities, certifications and past transactions, providing you with all the details to make confident decisions about your Mexican manufacturers." : "Cuando se trata de encontrar una fábrica, es importante tener toda la info que necesitas para tomar decisiones informadas. Con Puente, puedes olvidarte de las adivinanzas en la selección de proveedores con información precisa y reseñas completas y calificaciones de cada socio en nuestra red. Nuestros perfiles de proveedores te dan detalles sobre la experiencia, capacidades, certificaciones y transacciones pasadas de los fabricantes, dándote todo lo que necesitas para tomar decisiones seguras sobre tus fabricantes mexicanos."} image ={img2}/>
                    <SpotlightCard title ={props.lang ? "Streamlined Communication, Simplified Ordering." : "Comunicación ágil y pedidos simplificados."} subtitle = {props.lang ? "Use Our Dedicated Messaging and Ordering Platform for Seamless Communication and Easy Order Management." : "Usa nuestra plataforma de mensajería y pedidos pa' una comunicación fluida y fácil manejo de pedidos."} overview = {props.lang ? "From communicating with manufacturers to placing an order, the process of finding trustworthy maritime manufacturers in Mexico can be complicated and frustrating. With Puente, you can simplify the entire process with an easy-to-use messaging and ordering platform integrated into our system. Our dedicated messaging system allows you to communicate securely and quickly with suppliers, resulting in hassle-free communication. Placing an order couldn't be easier, with real-time updates and easy order management integrated into the platform. Get real-time tracking information and more, all in one place. With Puente, you can take the stress out of the entire supplier selection process, trusting our reliable information and streamlined platform." : "Desde comunicarte con fabricantes hasta hacer un pedido, el proceso de encontrar fábricas confiables en México puede ser complicado y frustrante. Con Puente, puedes simplificar todo el proceso con una plataforma de mensajería y pedidos fácil de usar integrada en nuestro sistema. Nuestro sistema de mensajería dedicado te permite comunicarte de forma segura y rápida con los proveedores, facilitando la comunicación. Hacer un pedido no podría ser más fácil, con actualizaciones en tiempo real y fácil manejo de pedidos integrados en la plataforma. Obten información de seguimiento en tiempo real y más, todo en un solo lugar. Con Puente, puedes quitarte el estrés de todo el proceso de selección de proveedores, confiando en nuestra información confiable y plataforma simplificada."} image ={img1}/>
                </div>
            </div>
        </section>
    )
}

export default FeaturesSpotlights
